spring:
  application:
    name: user-service-eureka-client
server:
  port: 9001

eureka:
  client:
    # Eureka Server ? ?? ?????? ??? ????? ??? ??? ???? ??
    fetch-registry: true
    register-with-eureka: true
    # Eureka Server URL Info
    service-url:
      defaultZone: http://localhost:8761/eureka

