spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: file:///Users/imwoo/study/git-local-repo
          default-label: master
server:
  port: 8888
