spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IMWoo94/Spring-Cloud-Microservice.git
          default-label: main
          skipSslValidation: true
          searchPaths: cloud-config
server:
  port: 8888
